#
# ZKVM Specific Versions and URLs
#

OPNEVM_BENCHMARK_REGZERO_ALIAS = "bmk-regzero"
OPNEVM_BENCHMARK_336F_ALIAS = "bmk-336f"
OPNEVM_BENCHMARK_F038_ALIAS = "bmk-f038"
OPNEVM_BASELINE_ARGUZZ_ALIAS = "bsl-arguzz"
OPENVM_BENCHMARK_REGZERO_COMMIT = "d7eab708f43487b2e7c00524ffd611f835e8e6b5"
OPENVM_BENCHMARK_336F_COMMIT = "336f1a475e5aa3513c4c5a266399f4128c119bba"
OPENVM_BENCHMARK_F038_COMMIT = "f038f61d21db3aecd3029e1a23ba1ba0bb314800"
OPENVM_BASELINE_ARGUZZ_COMMIT = "ca36de3803213da664b03d111801ab903d55e360"

OPENVM_AVAILABLE_COMMITS_OR_BRANCHES = [
    OPNEVM_BENCHMARK_REGZERO_ALIAS,
    OPNEVM_BENCHMARK_336F_ALIAS,
    OPNEVM_BENCHMARK_F038_ALIAS,
    OPNEVM_BASELINE_ARGUZZ_ALIAS,
    OPENVM_BENCHMARK_REGZERO_COMMIT,
    OPENVM_BENCHMARK_336F_COMMIT,
    OPENVM_BENCHMARK_F038_COMMIT,
    OPENVM_BASELINE_ARGUZZ_COMMIT,
]
OPENVM_ZKVM_GIT_REPOSITORY = "https://github.com/AnonForkBot/openvm.git"


def iter_openvm_snapshots() -> list[str]:
    return [
        OPNEVM_BENCHMARK_REGZERO_ALIAS,
        OPNEVM_BENCHMARK_336F_ALIAS,
        OPNEVM_BENCHMARK_F038_ALIAS,
        OPNEVM_BASELINE_ARGUZZ_ALIAS,
    ]


def resolve_openvm_commit(commit_or_branch: str) -> str:
    if commit_or_branch == OPNEVM_BENCHMARK_REGZERO_ALIAS:
        return OPENVM_BENCHMARK_REGZERO_COMMIT
    if commit_or_branch == OPNEVM_BENCHMARK_336F_ALIAS:
        return OPENVM_BENCHMARK_336F_COMMIT
    if commit_or_branch == OPNEVM_BENCHMARK_F038_ALIAS:
        return OPENVM_BENCHMARK_F038_COMMIT
    if commit_or_branch == OPNEVM_BASELINE_ARGUZZ_ALIAS:
        return OPENVM_BASELINE_ARGUZZ_COMMIT
    return commit_or_branch


RUST_TOOLCHAIN_VERSION = "nightly-2025-02-14"
